=== sacet2019/wt/ex7/Catalog.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="bookinfo">
<xs:complexType>
<xs:sequence>
<xs:element ref="Book" maxOccurs="unbounded"/>  //there is no maximum number of 
                                                                                                   occurrences.
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="Book">
<xs:complexType>
<xs:sequence>
<xs:element ref="Title" minOccurs="1" maxOccurs="1"/>
<xs:element ref="Author" minOccurs="1" maxOccurs="1"/>
<xs:element ref="Publication" minOccurs="1" maxOccurs="1"/>
<xs:element ref="Edition" minOccurs="1" maxOccurs="1"/>
<xs:element ref="ISBN" minOccurs="1" maxOccurs="1"/>
<xs:element ref="Price" minOccurs="1" maxOccurs="1"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="Title" type="xs:string"/>
<xs:element name="Author" type="xs:string"/>
<xs:element name="Publication" type="xs:string"/>
<xs:element name="Edition" type="xs:string"/>
<xs:element name="ISBN" type="xs:string"/>
<xs:element name="Price" type="xs:string"/>
</xs:schema>

=== sacet2019/wt/ex7/exp6bCatlogxsd-css.xml
<?xml version="1.0" encoding="UTF-8"?> 
<?xml-stylesheet type="text/css" href="library.css" ?>
<bookinfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Catalog.xsd">
<Book> 
<Title>XML Bible </Title>
<Author>Winston</Author>
<Publication>Wiely</Publication>
<Edition>Fifth Edition</Edition>
<ISBN>0-7645-4760-7</ISBN>
<Price>$40.5</Price > 
</Book>
<Book> 
<Title>Artificial Intelligence</Title>
<Author>S. Russel</Author>
 <Publication> Princeton Hall </Publication>
 <Edition> Sixth Edition</Edition> 
<ISBN> 0-13-1038-5-2 </ISBN>
 <Price>$60</Price> 
</Book> 
<Book> 
<Title>Java 2</Title>
<Author>Watson</Author> 
<Publication>BPB Publications</Publication>
<Edition>Third Edition</Edition>
<ISBN>0-41-1058-7-2</ISBN> 
<Price>$65</Price> 
</Book>
 <Book> 
<Title>HTML in 24 hours </Title>
<Author> Sam Peter</Author> 
<Publication> SAM Publications </Publication>
<Edition>Fifth Edition</Edition> 
<ISBN> 0-672-32841-0 </ISBN> 
<Price> $50 </Price > 
</Book> 
</bookinfo>
